const defaults={mode:'tropical',zoom:1,selected:'living',rooms:{living:{name:'Living room',area:'31 m²',mood:'Warm + social',purpose:'Gather, eat, watch storms roll in',flooring:'Polished concrete',items:[['▰','Cloud sofa'],['◉','Low table'],['♧','Areca palm'],['▤','Rattan chair'],['◫','Floor lamp']]},pma:{name:'PMA’s room',area:'16 m²',mood:'Quiet + breezy',purpose:'Sleep, draw, read by the window',flooring:'Local narra wood',items:[['▰','Platform bed'],['✎','Drawing desk'],['♧','Monstera']]},keisha:{name:'Keisha’s room',area:'15 m²',mood:'Bright + playful',purpose:'Rest, make music, catch sunrise',flooring:'Terrazzo',items:[['▰','Day bed'],['♫','Record player'],['◇','Woven rug']]},movie:{name:'Movie lounge',area:'19 m²',mood:'Dark + cozy',purpose:'Films, games, late-night karaoke',flooring:'Dark glass tile',items:[['▰','Modular sofa'],['▣','Projector'],['♫','Speakers']]},kitchen:{name:'Kitchen',area:'21 m²',mood:'Fresh + communal',purpose:'Cook, snack, leave notes',flooring:'Terrazzo',items:[['▥','Fridge'],['◒','Island'],['♨','Rice cooker'],['♧','Herb pots']]}} ,notes:[{text:'Mangoes are for everyone 🥭',by:'Keisha · 9:14'},{text:'Movie night at 8?',by:'PMA · Yesterday'},{text:'Please water the basil.',by:'Miko · Monday'}]};
let state=JSON.parse(localStorage.getItem('villaTogether')||'null')||structuredClone(defaults);let zoom=state.zoom||1;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const save=()=>{localStorage.setItem('villaTogether',JSON.stringify(state));$('#saveStatus').textContent='Saved just now'};const toast=t=>{const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)};
function renderRoom(){const r=state.rooms[state.selected];$('#roomName').textContent=r.name;$('#roomArea').textContent=r.area;$('#roomMood').textContent=r.mood;$('#purposeInput').value=r.purpose;$('#flooringSelect').value=r.flooring;$('#itemCount').textContent=`${r.items.length} items`;$('#dialogRoom').textContent=r.name;$('#roomItems').innerHTML=r.items.map((x,i)=>`<button class="item"><b>${x[0]}</b>${x[1]}<span class="remove" data-i="${i}" aria-label="Remove ${x[1]}">×</span></button>`).join('');$('.notes-panel').classList.toggle('visible',state.selected==='kitchen');$$('.hotspot').forEach(h=>h.classList.toggle('selected',h.dataset.room===state.selected));$$('.remove').forEach(b=>b.onclick=e=>{e.stopPropagation();r.items.splice(+b.dataset.i,1);save();renderRoom()});}
function renderNotes(){$('#notesList').innerHTML=state.notes.map(n=>`<div class="note">${n.text}<small>${n.by}</small></div>`).join('')}
$$('.hotspot').forEach(h=>h.onclick=()=>{state.selected=h.dataset.room;save();renderRoom();$('#inspector').classList.add('open')});$('.close-inspector').onclick=()=>$('#inspector').classList.remove('open');
$$('.mode').forEach(b=>b.onclick=()=>{$$('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mode=b.dataset.mode;$('#sceneWrap').classList.toggle('cyber',state.mode==='cyberpunk');save();toast(state.mode==='cyberpunk'?'Night City mood engaged':'Subtropical daylight restored')});
$('#zoomIn').onclick=()=>setZoom(Math.min(1.3,zoom+.1));$('#zoomOut').onclick=()=>setZoom(Math.max(.7,zoom-.1));function setZoom(z){zoom=state.zoom=Math.round(z*10)/10;$('#scene').style.transform=`scale(${zoom})`;$('#zoomLabel').textContent=Math.round(zoom*100)+'%';save()}
$('#renameBtn').onclick=()=>{const r=state.rooms[state.selected],name=prompt('Room name',r.name);if(name?.trim()){r.name=name.trim();save();renderRoom()}};$('#purposeInput').onchange=e=>{state.rooms[state.selected].purpose=e.target.value;save()};$('#flooringSelect').onchange=e=>{state.rooms[state.selected].flooring=e.target.value;save()};
const objects=[['▰','Lounge chair'],['♧','Tropical plant'],['◉','Side table'],['▤','Woven screen'],['◫','Pendant light'],['♫','Sound system'],['▣','Projector'],['◇','Handwoven rug'],['♨','Tea station']];$('#objectGrid').innerHTML=objects.map((x,i)=>`<button value="cancel" class="object-option" data-i="${i}"><b>${x[0]}</b>${x[1]}</button>`).join('');$('#addItemBtn').onclick=()=>$('#objectDialog').showModal();$$('.object-option').forEach(b=>b.onclick=()=>{state.rooms[state.selected].items.push(objects[+b.dataset.i]);save();renderRoom();toast('Object added')});
$('#noteForm').onsubmit=e=>{e.preventDefault();const input=$('#noteInput');if(!input.value.trim())return;state.notes.unshift({text:input.value.trim(),by:'You · just now'});input.value='';save();renderNotes();toast('Note left on the fridge')};
$('#shareBtn').onclick=()=>$('#shareDialog').showModal();$('#copyBtn').onclick=async()=>{await navigator.clipboard?.writeText($('#shareLink').value);$('#copyBtn').textContent='Copied';setTimeout(()=>$('#copyBtn').textContent='Copy link',1600)};
$('#soundBtn').onclick=()=>toast('Ambient island sounds are coming soon');$('#resetBtn').onclick=()=>{if(confirm('Reset your villa to the starting layout?')){state=structuredClone(defaults);save();location.reload()}};
$$('.rail-btn[data-tool]').forEach(b=>b.onclick=()=>{$$('.rail-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');const t=b.dataset.tool;if(t==='notes'){state.selected='kitchen';renderRoom();$('#inspector').classList.add('open')}else if(t==='decorate'){$('#objectDialog').showModal()}else if(t==='people')toast('PMA, Keisha and Miko are visiting');else if(t==='rooms')toast('Choose a room marker to edit it')});
setZoom(zoom);renderRoom();renderNotes();$('#sceneWrap').classList.toggle('cyber',state.mode==='cyberpunk');$$('.mode').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));

// WebMCP: the same villa actions are available to supporting AI browsers.
if(document.modelContext?.registerTool){
  const register=tool=>Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});
  register({name:'read_villa',title:'Read villa',description:'Read the current rooms, objects, notes and visual mode.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({mode:state.mode,selectedRoom:state.selected,rooms:state.rooms,notes:state.notes})});
  register({name:'select_room',title:'Select room',description:'Select a room in the visible villa inspector.',inputSchema:{type:'object',properties:{roomId:{type:'string',enum:['living','pma','keisha','movie','kitchen']}},required:['roomId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:({roomId})=>{if(!state.rooms[roomId])throw new Error('Unknown room');state.selected=roomId;save();renderRoom();return{selectedRoom:roomId,name:state.rooms[roomId].name}}});
  register({name:'add_villa_object',title:'Add villa object',description:'Add a named decorative or functional object to one room.',inputSchema:{type:'object',properties:{roomId:{type:'string',enum:['living','pma','keisha','movie','kitchen']},name:{type:'string',minLength:1,maxLength:40},symbol:{type:'string',maxLength:3}},required:['roomId','name'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:({roomId,name,symbol='◇'})=>{if(!state.rooms[roomId]||!name?.trim())throw new Error('Valid roomId and name required');state.rooms[roomId].items.push([symbol,name.trim()]);save();renderRoom();return{added:name.trim(),roomId,itemCount:state.rooms[roomId].items.length}}});
  register({name:'leave_fridge_note',title:'Leave fridge note',description:'Post a short shared note on the kitchen refrigerator.',inputSchema:{type:'object',properties:{text:{type:'string',minLength:1,maxLength:90},author:{type:'string',minLength:1,maxLength:30}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:({text,author='Guest'})=>{if(!text?.trim())throw new Error('Note cannot be empty');state.notes.unshift({text:text.trim(),by:`${author} · just now`});save();renderNotes();return{posted:true,noteCount:state.notes.length}}});
}
